const { Data } = require("pipedrive");

// sample Data
const contacts = {
  contactID: "bc80f243-9443-4fda-8704-41f94790d8f1",
  accountNumber: "CUST100",
  contactStatus: "ACTIVE",
  name: "Apex Wiring Solutions Pty Ltd",
  firstName: "Simon",
  lastName: "Waldren",
  emailAddress: "simon@apexwiringsolutions.com",
  contactPersons: [],
  bankAccountDetails: "",
  addresses: [
    {
      addressType: "STREET",
      addressLine1: "Suite 11/296 Bayside Rd",
      addressLine2: "",
      addressLine3: "",
      addressLine4: "",
      city: "CHELTENHAM",
      region: "VIC",
      postalCode: "3192",
      country: "",
      attentionTo: "",
    },
    {
      addressType: "POBOX",
      addressLine1: "Suite 11/296 Bayside Rd",
      addressLine2: "",
      addressLine3: "",
      addressLine4: "",
      city: "CHELTENHAM",
      region: "VIC",
      postalCode: "3192",
      country: "",
      attentionTo: "",
    },
  ],
  phones: [
    {
      phoneType: "DDI",
      phoneNumber: "",
      phoneAreaCode: "",
      phoneCountryCode: "",
    },
    {
      phoneType: "DEFAULT",
      phoneNumber: "",
      phoneAreaCode: "",
      phoneCountryCode: "",
    },
    {
      phoneType: "FAX",
      phoneNumber: "",
      phoneAreaCode: "",
      phoneCountryCode: "",
    },
    {
      phoneType: "MOBILE",
      phoneNumber: "",
      phoneAreaCode: "",
      phoneCountryCode: "",
    },
  ],
  isSupplier: false,
  isCustomer: true,
  updatedDateUTC: "2020-07-10T06:43:34.840Z",
  contactGroups: [],
  balances: {
    accountsReceivable: { outstanding: 1540, overdue: 1540 },
    accountsPayable: { outstanding: 0, overdue: 0 },
  },
  hasAttachments: false,
  hasValidationErrors: false,
};
